version: '3'

services:

  mongo:
    healthcheck:
      test: ["CMD-SHELL", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"